BeginMain = "🚌"
PlusOperator = "🎁"
MinusOperator = "💳"
MultiplicationOperator = "👪"
DivisionOperator = "✂"
ModuloOperator = "💣"
EndMain = "🎓"
Print = "🖊"
AssignVariable = "🖘"
PlusEquals = "💪"
MinusEquals = "🔫"
False = "👎"
True = "👍"
EqualTo = "❤"
NotEqualTo = "💔"
GreaterThan = "🐘"
And = "🐜"       # Ant
Or = "🐗"        # Boar
If = "😸"        # Grinning Cat
Else = "😾"      # Pouting Cat
ElseIf = "😼"    # Wry Cat
EndIf = "🙀"     # Weary Cat
While = "🏃"     # Runner
EndWhile = "🚶"   # Pedestrian
Return = "🚣"
DeclareMethod = "🙉" # Monkey Hear-no-evil
EndMethod = "🙊"     # Monkey Say-no-evil
CallMethod = "🙈"    # Monkey See-no-evil
LessThan = "🐁"
RaiseException = "🖕"
Loop = "⭕"
BreakLoop = "🔨"
BeginLambda = "🌜"
EndLambda = "🌛"
End = "👏"       # Applause
